Documentation/Faq/Index.rst

For TYPO3 newcomers it would be useful to know that it's possible to restrict TSConfig settings (eg. hiding fields) to specific user groups.

[ADD] Add TS conditions hint

---

Classes/Finisher/SendParametersFinisher.php
Documentation/ForAdministrators/BestPractice/SendingValuesToThirdPartySoftware/Index.rst

Add new Typoscript Settings to use Basic Auth Protection in SendParametersFinisher.
If username and password is empty, the target url is called without protection

[FEATURE] Allow Basic Auth Protection for SendParametersFinisher

---

Classes/Tca/ShowFormNoteEditForm.php

If there was already a content element and you call the new wizard to create a form, it fails due to the fact that TYPO3 provides the inverted uid of the content element after which the new one should be placed instead of the page id.

[BUGFIX] Wrong page id for new wizard

---

Classes/Domain/Repository/MailRepository.php
Documentation/ForDevelopers/SignalSlots/Index.rst

the getVariablesWithMarkersFromMail signal is ment for adding custom makrers/variables to the template (or modyfing existing ones).
The marker values passed to the signal are already transformed (e.g. converted to string and imploded).
The $mail object is now passed to the slot, so the slot can access field original data.

Pass $mail to getVariablesWithMarkersFromMail signal

---

Classes/Utility/TemplateUtility.php

currently, if you want to use your own fluid templates for sent mails, they are not found by powermail (falling back to hardcoded default paths) because the TypoScript configuration `plugin.tx_powermail` is not loaded.

[BUGFIX] load powermail TypoScript in mail standaloneView

---

.gitattributes

* The .gitattributes file makes exports from github a bit smaller
* by removing not required files for production
* Usefull for composer instalation

[TASK] Exclude non-production files from Git archives

---

Classes/Tca/FormSelectorUserFunc.php

* Due to a breaking change in the core API of TYPO3 CMS 7.6, $params[‘row’] was moved to $params['flexParentDatabaseRow’]. When inserting the powermail plugin (pi1) in the backend, localized forms without a relation to a default language record could not be selected.
See: https://docs.typo3.org/typo3cms/extensions/core/Changelog/7.6/Breaking-70132-FormEngineCustomFunctions.html

[BUGFIX] Make localized forms selectable

---

Resources/Private/JavaScripts/Powermail/Form.js

The problem was, that data-powermail-ajax-uri="event-pages/.../.../" was directly added to current URL in Internet Explorer IE11 and lower.

AjaxFormSubmit IE window.location bug

---

Configuration/TCA/tx_powermail_domain_model_field.php

`tx_powermail_domain_model_field.pages` is defined with `l10n_mode=exclude`
which leads the situation that the parent pointer value is overridden
with the value of the default language record of the field entity.
Related: https://forge.typo3.org/issues/80311
Related: https://forge.typo3.org/issues/80281
Fixes: #55

[BUGFIX] Field parent pointer of translation overridden in TYPO3 CMS 8

---

Configuration/FlexForms/FlexformPi1.xml

On save CKEditor adds empty p-tags in powermail plugin in RTE-fields
Bug fixed. Side affects should not happen.
Thanks to Thomas Scheibitz (@scheibo_)

Implements https://forge.typo3.org/issues/81015

---

Resources/Private/Templates/Form/Confirmation.html
Resources/Private/Templates/Form/Form.html

This scrolls the form into view when submitting the form,
which is helpful for longer pages with the powermail form at the bottom.
Resolves: https://github.com/einpraegsam/powermail/issues/72

[FEATURE] Scroll down to form when reloading page

---

Classes/Domain/Service/SendMailService.php

When the sender mail and sender e-mail is empty, TYPO3's settings
for those will be used.
Resolves: https://github.com/einpraegsam/powermail/issues/74

[FEATURE] Use default TYPO3 settings when sender name/email is empty

---

Classes/ViewHelpers/Condition/IsArrayViewHelper.php
Classes/ViewHelpers/Condition/IsDateTimeVariableInVariableViewHelper.php
Classes/ViewHelpers/Condition/IsNumberViewHelper.php
Classes/ViewHelpers/Misc/VariableInVariableViewHelper.php
Classes/ViewHelpers/String/UnderscoredToLowerCamelCaseViewHelper.php

The main motivation is the performance gain, but also in the longer run (TYPO3v9), TYPO3 core will deprecate the usage of arguments on render method. 
Following viewhelpers were changed:
- String/UnderscoredToLowerCamelCaseViewHelper
- Condition/IsArrayViewHelper
- Condition/IsDateTimeVariableInVariableViewHelper
- Condition/IsNumberViewHelper
- Misc/VariableInVariableViewHelper
Other viewhelpers should follow the path. You can test all viewhelpers in one action by trying to export record to xls.

Make few viewhelpers compilable to improve performance

---

Classes/Domain/Repository/MailRepository.php

Fix big memory consumption on the backend module list view, by reducing iteration to just unique Forms Uids.
In our TYPO3 we have almost 30k unique mails from one Form and memory was reduced from ~720MB to ~12MB.

[PR] backend module list view memory usage fix

---

Classes/Domain/Model/Mail.php

It seems to make things faster, at least in the backend module. 
Or is there a reason for not having this?

[TASK] Add lazy annotation for feuser

---

Classes/Domain/Repository/MailRepository.php

(Resolves Issue #120, not sure if this is actually a bug in Typo3)

[BUGFIX] Clear persistenceManager state after findGroupedFormUidsToGivenPageUid

---

Configuration/TypoScript/Marketing/setup.txt

Most people use 'L' as the language parameter but this is not mandatory.

[BUGFIX] Use 'TSFE:sys_language_uid' instead of 'GP:L' for marketing info

---

Classes/Domain/Validator/SpamShieldValidator.php
Configuration/TypoScript/Main/setup.txt
Documentation/ForAdministrators/BestPractice/SpamPrevention/Index.rst

This change introduces a new setting,
plugin.tx_powermail.setup.spamshield.senderEmail
If set, outgoing spam notifications will be sent "from" this address.
If left empty, outgoing spam notifications‘ from will default to
powermail@[your-domain] which had been hard-coded so far.
See https://github.com/einpraegsam/powermail/issues/121

[FEATURE] Make sender email of spam admin notifications configurable

---

Classes/Controller/ModuleController.php
Resources/Private/Partials/Module/List.html

Only show the "edit", "delete" and "hide" buttons if the current backend user
is allowed to modify the _answer and _mail tables.

[FEATURE] Check write access to mail tables in backend module

---

Classes/Domain/Service/SendMailService.php

Add public getters to allow access to protected variables $settings,
$configuration and $overwriteConfig in SignalSlots.

[TASK] Add getters for $settings, $configuration and $overwriteConfig in sendMailService

---

Classes/Tca/FormSelectorUserFunc.php

Use BackendUtility::getRecordTitle instead of the hardcoded
title to make it possible to change the used label of a form.
Resolves: #165

[TASK] Use BackendUtility::getRecordTitle inside FlexForms

---

Resources/Private/JavaScripts/Powermail/Tabs.js

The function `$.listen` is only defined when `parsley.js` is included. Thus we should check first whether parsley is loaded or not otherwise the following error is thrown:
`Uncaught TypeError: e.listen is not a function`

Fixes error "e.listen is not a function" when parsley is not included

---

Classes/Domain/Validator/InputValidator.php

When extending the Model\Files object, the comparison of the $answer->getField() and $field fails and the field validation fails. To make validation work again, the comparison should be reduced to the objects' uid.
See issue #175 for more information

Compare only objects' uids during validation

---

Classes/Domain/Repository/PageRepository.php

The automatic language and workspace overlay data loader expects the uid
of a record to be available.
Resolves: https://github.com/einpraegsam/powermail/issues/196

[BUGFIX] Do not crash backend module in workspace

---

Classes/Controller/FormController.php

TYPO3's syslog is full of warnings so that one does not really want to
log them all, but mail sending failures are something that should
be visible in the log.

[BUGFIX] Log mail sending errors as error, not as warning

---

Classes/Domain/Service/Mail/SendMailService.php
Documentation/ForDevelopers/SignalSlots/Index.rst

- Updated documentary because the namespace for the example has changed.
- Added updating ReceiverMail in Classes/Domain/Service/Mail/SendMailService.php->updateMail() or is there a reason why it's missing?

update "sendTemplateEmailBeforeSend" Signal-Slot

---

Resources/Private/Partials/Module/Export.html

As hidden can be a crucial information, e.g. regarding double-opt in, it should be available in the export.
Resolves: #229

[TASK] Add field hidden to possible export fields

---

Classes/ViewHelpers/Validation/ValidationDataAttributeViewHelper.php

Hi, I am using powermailextended a lot and have create new fields that also are an 'input' although their type name, of course, differs.
With this change I can re-use this method by extending the `ValidationDataAttributeViewHelper`.
A solid solution would be to not use `getType()`  for this type of capability tests at all. Instead, every field needs to declare its capabilities (file upload, multiple, advanced file type, etc.). Currently there are different approaches for this: 
* `isAdvancedFieldType()`, 
* field type in `page.ts`, 
* maybe also `isMultiselect()` etc.

Validation for extended fields

---

Classes/Domain/Service/Mail/PlaintextService.php
Tests/Unit/Domain/Service/Mail/PlaintextServiceTest.php

Hey Alex!
The current implementation of `In2code\Powermail\Domain\Service\Mail\PlaintextService->makePlain` does not account for multi line `<head>` tags (because of missing `s` modifier) nor for further invisible tags. That is especially important when you want to add style to your emails. Since the `<style>` tag should be within the `<body>` tag for extended email client support, it is not enough to remove the `<head>` tag.
What do you think?
Kind regards
Markus

[BUGFIX] Remove multi line head tags and further invisible tags

---

Documentation/ForAdministrators/BestPractice/MainTypoScript/Index.rst

It took me a while to figure out why a customer system repeatedly tried to send e-mails with powermail@[customer domain]. Since allowed sender e-mail addresses need to be explicitly white-listed on this system bounce messages flooded the mail log. Browsing the code revealed that spamshield.senderEmail is available as settings option. I think it might be a good idea to add this option to the documentation.

Updated spamshield documentation

---

Tests/Behavior/readme.md

When running `composer update`, I get the following error:
nimut/testing-framework 1.1.9 requires php >=5.3 < 7.2 -> your PHP version (7.2.4) does not satisfy that requirement.
testing-framework has new major versions that allow 7.2 - can you please test them and update the composer.json?
Until then, the workaround is to use PHP 7.1 or lower.

Testing framework requires PHP < 7.2

---

Configuration/TSConfig/WebList.typoscript
ext_localconf.php

At the moment the tables in the list view of the backend are sorted alphabetically. A storage with forms, mails... looks like this: 
- Answers
- Fields
- Forms 
- Mails
- Pages
This PR changes the order of the tables to the following: 
- Mails
- Answers
- Forms
- Pages
- Fields
This is possible by using a feature of PageTSconf introduced in TYPO3 7.4 - [Feature #65550](https://docs.typo3.org/typo3cms/extensions/core/Changelog/7.4/Feature-65550-MakeTableDisplayOrderConfigurableInListModule.html)
By using inline TCA the editor can create a form which contains pages which are containing fields. 
Reproducing this hierarchical structure in the list would make it easier to find the element you are looking for. 
Just a small change, but I found it to be quite a good improvement in the backend …

Change display order of tables in backend list view

---

Resources/Private/Templates/Output/Delete.html
Resources/Private/Templates/Output/Edit.html
Resources/Private/Templates/Output/List.html
Resources/Private/Templates/Output/Show.html

For identifying in which view we are in, to be able to style it without overriding the template (I did it because of list/show, added the others for consistency)

Add actions as css classes to powermail_frontend

---

Classes/ViewHelpers/Misc/GetFileWithPathViewHelper.php

When listing an upload that is not available via public url, the ViewHelper crashes on  forced ```:string``` return type in function.
Typecasted the value to string, to return empty string instead of ```null```;

[BUGFIX] Force string value on possible nullable return

---

ext_tables.sql

Without this patch powermail queries are popping up in mysql slow log.
e.g.
```
SELECT  tx_powermail_domain_model_page.* FROM tx_powermail_domain_model_page  WHERE tx_powermail_domain_model_page.forms = 104 AND tx_powermail_domain_model_page.deleted=0 AND tx_powermail_domain_model_page.t3ver_state<=0 AND tx_powermail_domain_model_page.pid<>-1 AND tx_powermail_domain_model_page.hidden=0 AND tx_powermail_domain_model_page.starttime<=1534415100 AND (tx_powermail_domain_model_page.endtime=0 OR tx_powermail_domain_model_page.endtime>1534415100) ORDER BY tx_powermail_domain_model_page.sorting ASC
```
or
```
SELECT  tx_powermail_domain_model_field.* FROM tx_powermail_domain_model_field  WHERE tx_powermail_domain_model_field.pages = 174 AND tx_powermail_domain_model_field.deleted=0 AND …
```

Add db indices for the page and field tables

---

Documentation/ForAdministrators/BestPractice/MainTypoScript/Index.rst

The default value of misc.randomizeFileName in typoscript constants is 1, not 0.

Fix default value of randomizeFileName

---

Classes/Domain/Model/Field.php
Classes/Hook/CreateMarker.php

Assume a field is localized only when its sys_language_uid and l10n_parent are greater than 0. Closes #329.

[BUGFIX] Markers in non-default language fields

---

Documentation/ForDevelopers/AddNewFieldProperties/Index.rst

Changed ViewHelper from vh:string.RawAndRemoveXss to vh:string.escapeLabels in documentation (RawAndRemoveXss has been removed in v5.0)

Changed ViewHelper from vh:string.RawAndRemoveXss to vh:string.escapeLabels

---

Configuration/TypoScript/Main/setup.txt

Since links are not <link> tags but proper <a> tags those tags need to be absolute-ified as well.
Related: #114

Ensure <a> tags are rendered with absolute URLs

---

Documentation/Includes.txt
Documentation/Settings.cfg
composer.json

The generation of rst files on docs.typo3.org changed. Theses changes
are necessary to make the work.
Additionally there are two more steps to do: 
* setup a new webook
* contact the documentation team for a redirect
More information on these two steps:
https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Migrate.html

[FEATURE] Use the new documentation rendering process

---

Classes/Controller/FormController.php

Would be nice if you would add this signal so that one can invoke another process after optinMail has been confirmed and persisted.

Add signal optinConfirmActionAfterPersist

---

Classes/Domain/Model/Field.php

I would suggest changing it to int as this doesn't require a database update on the typo3 installation.
Ref #402

[BUGFIX] Changing Field.content_element to int

---

Classes/Domain/Validator/SpamShield/LinkMethod.php

Fixes: TypeError: preg_match_all() expects parameter 2 to be string, boolean given
typo3conf/ext/powermail/Classes/Domain/Validator/SpamShield/LinkMethod.php in preg_match_all

Bugfix: Search for links in string answers only

---

Classes/Domain/Validator/UploadValidator.php

When using a fileupload in a form with double opt-in the uploadvalidator can
not directly access the form (mail is not an array as when the form is actually sent,
it is a string with the mail uid instead).
So a workaround is to get the form from the mail uid that is delivered within the confirmation link of tha double opt-in process.

[BUGFIX] UploadValidation hangs up when using double Opt-In

---

Classes/Domain/Service/Mail/SendMailService.php
Documentation/ForAdministrators/BestPractice/Debug/Index.rst

Currently it is not possible to hook into the sending process and prevent sending the email altogether.
I am using this feature to decide in the hook based on the saved Answers whether the email should be sent now - or later (similar to the optinConfirm-Flow). Another Usecase would be to dynamically decide whether the receiver template email should be sent or not.
Also, I have updated the logging documentation.

[FEATURE] Abort the Email-Send process by signal

---

Classes/Domain/Repository/MailRepository.php

When activating the "double opt-in" plugin setting,
new mail records are disabled until confirmed.
The uniqueness check failed in this case because only enabled mails
were taken into account.
Resolves: https://github.com/einpraegsam/powermail/issues/509

[BUGFIX] Let global "unique" validator look into disabled mails

---

Classes/Utility/FrontendUtility.php
Configuration/Extbase/Persistence/Classes.php
ext_typoscript_setup.txt

We're upgrading a TYPO3 project and we came across an error on submitting a powermail form while the user is logged in as an FE user. 
1.) there seems to be a migration missing of "config.tx_extbase.persistence".
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html for more details. 
2.) getPropertyFromLoggedInFrontendUser() in FrontendUtility.php has a type declaration for the return value: It must be a string. But a uid is no string... I'm fixing this problem with a cast of the result.

[Bugfix] TYPO3 10.4 Error on submit if logged in as FE user

---

Classes/Domain/Repository/FieldRepository.php

findByMarkerAndFormAlternative() is called in findByMarkerAndForm() which may return a field
Solves: #539

Bugfix: TypeError in findByMarkerAndFormAlternative()

---

Configuration/TypoScript/Powermail_Frontend/setup.typoscript

The symfony conditions do not seperate single conditions with square
brackets. They only have a square bracket at the beginning and the
end.
Fixes: #554

[BUGFIX] Fix condition syntax for powermail_frontend

---

Classes/Domain/Factory/MailFactory.php
Classes/Utility/SessionUtility.php

The method `In2code\Powermail\Utility::getSessionValuesForPrefill` must return an array, but `getSessionValue` could return a string if no session is set.
This change will ensure that `In2code\Powermail\Utility::getSessionValue` returns an array.

[BUGFIX] Session value for form prefill is expected to be an array

---

Documentation/ForDevelopers/AddNewFields.md

A piece of the path was missing in the documentation.

Path corrected

---

Classes/Utility/TemplateUtility.php

Ensures the function will always return a string.
When the passed variable `$string` is a non existing fluid variable (e.g. `{foo}`), then `$standaloneView->render()` will return `null`. 
Possible Fluid core issue.

[TASK] Harden TemplateUtility::fluidParseString()

---

Classes/Utility/TemplateUtility.php

**The Problem / Issue / Bug:**
In a project with multiple template paths, the paths are not sorted numerically. As a result, the paths are processed in the wrong order according to possible templates and individualization is not possible.
**How this PR Solves The Problem:**
With this bugfix the template paths are sorted according to the numerical value, which was defined via TypoScript.
**Manual Testing Instructions:**
1. Add an additional template path in TypoScript (via the constants)
2. Outsource the template "/Templates/Form/Form.html" in the defined path
3. Change the template, e.g. by adding static text
**Result:**
Without this bugfix, the default template (Form.html) from EXT:powermail is always used. With this bugfix the modified template is used.
**Tested version:**
* powermail …

[BUGFIX] Fix template ordering by respect the numeric template index

---

Configuration/TCA/tx_powermail_domain_model_answer.php
Configuration/TCA/tx_powermail_domain_model_field.php
Configuration/TCA/tx_powermail_domain_model_form.php
Configuration/TCA/tx_powermail_domain_model_mail.php
Configuration/TCA/tx_powermail_domain_model_page.php

Show sys_language_uid labels for values 0 and -1 again for TYPO3 9.5 (powermail 7.x)
Cherry-picked to branch 7.x from #471

[BUGFIX] Show sys_language_uid labels for values 0 and -1 again (7.x)

---

Classes/Controller/FormController.php
Classes/Finisher/SendParametersFinisher.php

As an expected behaviour is caught, the logger should not
output "Alert: action must be taken immediately". Therefor
the severity of the message is lowered to warning.
Related: #487

[TASK] Lower severity for logger

---

Classes/Utility/TypoScriptUtility.php

Fixes `Argument 2 passed to In2code\Powermail\Utility\TypoScriptUtility::overwriteValueFromTypoScript() must be of the type array, null given, called in /typo3conf/ext/powermail/Classes/Domain/Service/Mail/SendMailService.php on line 447` as reported in #649.

[BUGFIX] Allow $conf to be NULL

---

Classes/Domain/Model/Answer.php

Ensure that the method In2code\Powermail\Domain\Model\Answer::convertToJson()
does always return a string even if a non string value like null is given.

Fix invalid return type

---

Configuration/TCA/tx_powermail_domain_model_answer.php
Configuration/TCA/tx_powermail_domain_model_field.php
Configuration/TCA/tx_powermail_domain_model_form.php
Configuration/TCA/tx_powermail_domain_model_mail.php
Configuration/TCA/tx_powermail_domain_model_page.php

Adopt TCA of starttime / endtime fields and reduce not needed options.
Furthermore a possible regression of the core is avoided as it is not
possible to clear the field once set.

[TASK] Simplify TCA of date fields

---

Classes/Domain/Factory/FileFactory.php

Could not reproduce the error with a form submit but found errors in the error log indicating that this somehow can be triggered.
```
PHP Warning: mime_content_type(...uploads/tx_powermail/stephaniewyntershhz603_gmail.com): failed to open stream: No such file or directory in ...typo3conf/ext/powermail/Classes/Domain/Factory/FileFactory.php line 138
Uncaught TYPO3 Exception: Argument 1 passed to In2code\Powermail\Domain\Model\File::setType() must be of the type string, bool given, called in ...typo3conf/ext/powermail/Classes/Domain/Factory/FileFactory.php on line 140 | TypeError thrown in file ...typo3conf/ext/powermail/Classes/Domain/Model/File.php in line 223
```
I also chose to use TYPO3 mime type API instead of the function call and to add a fallback in case even this fails, to avoid …

Fix fatal errors when file size or type is not given

---

Resources/Private/Partials/Module/Search.html

The label "Reduce to one form" needs an own id and proper relation to the field

[BUGFIX] Use correct label in backend module search

---

Resources/Private/Build/JavaScript/FormValidation.js

**Test**
1. Form with at least one mandatory-field, reset-field and submit-field
2.  Click on submit
**current behavior without fix**
Form is submitted to server with an js-error in console ("Uncaught TypeError: e.getAttribute(...) is null") although there are validation errors.
**behavior with this fix**
Form is not submitted and js-errors are shown.

[BUGFIX] Exclude reset-field from validation

---

Classes/Hook/CreateMarker.php

When saving a field of type "Content" an error occured, this is fixed with this patch.

[FIX] Fixes Problem with Saving Content Element Fields

---

Resources/Private/Partials/Form/Field/Html.html

The TypoScript setting
plugin.tx_powermail.settings.misc.htmlForHtmlFields = 1
had no effect because of a wrong usage of viewhelpers.

[BUGFIX] Render HTML of HTML-Fields

---

Resources/Private/Partials/Misc/HoneyPod.html

The configured value `new-powermail-hp` for the autocomplete attribute is invalid and fails in the accessibility check provided by accessibilityinsights.io
AFAIK, valid values for autofill are:
* https://www.w3.org/TR/html52/sec-forms.html#autofilling-form-controls-the-autocomplete-attribute
* https://www.w3.org/TR/WCAG21/#input-purposes

[TASK] Hide honeypot field from screenreaders 

---

Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf

Minor spelling and grammar fix.
------
Not in commit message:
Usually, in the other texts, the word "email" is used, instead
of "mail", so this was changed as well.
In other texts there is some capitalization of the main term,
so Email was capitalized as well (even though grammatically
this might not be correct except for titles or common names).

[TASK] Improve text for error_mail_not_created

---

Classes/Controller/ModuleController.php

$this->htmlResponse() will overwrite the "Content-Type" header in its function call, so it is always "text/html" which will not trigger a download if you export via the backend module

[BUGFIX] set header via response api

---

Resources/Private/Language/de.locallang_db.xlf

Fixes a little typo in error warning for empty field name

[TASK] Fix little typos in de.locallang_db.xlf

---

Configuration/Extbase/Persistence/Classes.php

There was an error in the table mapping for be_users and be_groups, so setting up backend groups as receivers did not work.
See #1036

[BUGFIX] Use correct table mapping for be_users and be_groups

---

Classes/Controller/ModuleController.php

There's an exception when hitting the XLS export button on a folder without mail records. This fixes that.

[BUGFIX] Fix exception when trying to XML export zero mail records

---

Configuration/FlexForms/FlexformPi1.xml
Configuration/FlexForms/FlexformPi2.xml

According to deprecation [#97126](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97126-TCEformsRemovedInFlexForm.html), the FlexForm tag TCEforms is no longer necessary and must be removed.

[TASK] Remove deprecated TCEforms FlexForm tag

---

Configuration/FlexForms/FlexformPi1.xml

"defaultExtras" has already been removed in TYPO3 v8.6.
Furthermore, the "richtextConfiguration" has also been removed, as it is only initialized with "default", which TYPO3 automatically falls back to. However, not setting it allows it to be overwritten via PageTS
Fixes: #1065
Related: #262

[TASK] Remove "defaultExtras"

---

Classes/Update/PowermailPermissionUpdater.php

There might be situation, where the `explicit_allowdeny` column is null. (Probably very old installations, where the column had null as default. Providing an empty string as a fallback solves the issue.
Related: in2code-de/powermail#1062
Related: in2code-de/powermail#1019

[BUGFIX] Provide a fallback for null values

---

Classes/Domain/Repository/PageRepository.php
Classes/Tca/FormSelectorUserFunc.php

This PR fixes a bug inside `PageRepository::getPropertiesFromUid()` when a non-existent page is queried. In this case, the result is `false` instead of an array. This was already addressed with 618f5ec804063c03c9bb9feb3591b2d742460705, but is obviously missing in more recent versions of the extension.
Resolves: #874

[BUGFIX] Handle lookup of properties of non-existing page

---

Classes/Domain/Validator/ForeignValidator.php

Related: in2code-de/powermail#1105

[BUGFIX] Prevent undefined array key warning in ForeignValidator::class

---

Configuration/FlexForms/FlexformPi1.xml

Use TYPO3 renderType selectMultipleSideBySide to allow for filtering when selecting a form in the plugin.
This provides better usability when there are many forms.
Related: in2code-de/powermail#934

[FEATURE] Use side-by-side select form forms

---

Classes/ViewHelpers/Misc/ManipulateValueWithTypoScriptViewHelper.php
Documentation/ForAdministrators/BestPractice/ManipulateValuesFromPowermailAll.md

Without this patch it's not possible to use `manipulateVariablesInPowermailAllMarker` to manipulate selected values of an array field such as checkboxes and multiselect.
Additionally it's now possible to access an options label as defined in a fields settings.
Example:
plugin.tx_powermail.settings.setup {
manipulateVariablesInPowermailAllMarker {
optinMail {
my_checkboxes = CASE
my_checkboxes {
key.field = value
1 = TEXT
1.value = Override for option value 1
default = TEXT
default.field = label
}
}
}
}
This patch can be backported to `10.7.x` too.
Resolves: #956

[BUGFIX] Fix broken manipulateVariablesInPowermailAllMarker for arrays

---

Resources/Private/Partials/Module/Export.html

As all filter requests are forwarded from the dispatch action to the list action, the request is evaluated as "invalid" and submitted form values are used by default. To ensure the current (new) field uids for an export are taken into account, the corresponding attribute "respectSubmittedDataValue" needs to be set.
Maybe related to: #1180
Resolves: #1089

[BUGFIX] Set correct export field uids

---

.github/workflows/testing.yaml

Github is dropping support for old images. So we update to the latest ubuntu lts images.

[TASK] Update ubuntu images in gh workflows

---

Classes/Controller/FormController.php
Classes/Events/FormControllerFormActionEvent.php

In event FormControllerFormActionEvent, make it possible to assign variables to view.
Resolves: #1198

[FEATURE] Make it possible to assign variables to view

---

Classes/Controller/AbstractController.php
Documentation/Index.md
composer.json
ext_emconf.php

- raise version numbers
- suggest the direct use of `phpoffice/phpspreadsheet` via composer
- suggest `EXT:base_excel` for legacy installations
- test for class existence of PhpSpreadSheet
Related: in2code-de/powermail#1214
Related: in2code-de/powermail#1208

[TASK] Use phpspreadsheet consistently

---

Classes/Command/ExportCommand.php
Classes/Command/FakeRequestTrait.php
Resources/Private/Templates/Module/ExportXls.html

In the CLI mode it's now necessary to implement a fakeRequest for this command.
Also the strftime is replaced and the exportxls template needs to have the extensionName param inside the f:translate tags.

[BUGFIX] Exportcommand not working

---

Classes/Controller/FormController.php

The $mail argument needs to be optional so we can
act if the object is not given.
fixes #969

[BUGFIX] fix checks for invalid action arguments

---

Configuration/Sets/Main/settings.definitions.yaml

The current view settings in the _Main_ site set settings definition file are incorrectly defined under `plugin.tx_powermail.settings.view.*`, which causes them to be ignored.  
This patch corrects the configuration keys to the proper format (by removing settings.) so they are recognized and used:
```
plugin.tx_powermail.settings.view.templateRootPath => plugin.tx_powermail.view.templateRootPath
plugin.tx_powermail.settings.view.partialRootPath => plugin.tx_powermail.view.partialRootPath
plugin.tx_powermail.settings.view.layoutRootPath => plugin.tx_powermail.view.layoutRootPath
```

[BUGFIX] fix site set settings definitions for view settings

---

Configuration/Sets/Main/setup.typoscript
Configuration/Sets/Marketing/setup.typoscript
Configuration/Sets/Styling/setup.typoscript

The TypoScript import paths in the site sets _Main_, _Marketing_ and _Styling_ are incorrect.
This bugfix sets the correct import paths to the TypoScript files.
Additional note:  
The site set _DropInFrontend_ references the path EXT:powermail/Configuration/TypoScript/Powermail_Frontend but this path does not exist any more.  
The site set should probably be removed, since the related plugins and TypoScript have also been removed recently: https://github.com/in2code-de/powermail/commit/992d4b8d0cf63bd672a15ce6af481d04d1f592c1

[BUGFIX] fix import paths in SiteSet TypoScript setup files

---

Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_db.xlf
Resources/Private/Language/locallang_mod.xlf

Since crowdin translations are solely based on the master branch, these translations and labels are also used for TYPO3 v12 compatible releases. In order to provide translations for old versions, we need to re-add that stuff.
Related: in2code-de/powermail#1272

[BUGFIX] Re-add labels for powermail frontend
