- Classes/Domain/Factory/FileFactory.php
- Classes/Domain/Model/Field.php
- Classes/Domain/Model/Form.php
See https://forge.typo3.org/issues/78409
> Fixing #78409: Adding a new field of type file is not possible

- Documentation/ForDevelopers/AddNewFields/Index.rst
Partial path needs to be extended, not the template path.
> Fix example TypoScript code

- Documentation/ForDevelopers/AddFinisherClasses/Index.rst
:file:`DoSomethingFinisher.php`
> add the name of the php file

- Documentation/ForAdministrators/BestPractice/DateConverterUserFunc/Index.rst
> [BUGFIX] Fix syntax in documentation - DateConverter UserFunc

- Classes/Domain/Service/GetNewMarkerNamesForFormService.php
- Tests/Unit/Domain/Service/GetNewMarkerNamesForFormServiceTest.php
Bugfix related to issue on forge.typo3.org 
https://forge.typo3.org/issues/79036
> [BUGFIX] Better marker generation (convert accented characters to ASCII equivalents

- Documentation/ForEditors/AddANewForm/FieldInput/Index.rst
> Mention zip code problem in "number" validation.

- Configuration/TypoScript/BootstrapClassesAndLayout/constants.txt
- Configuration/TypoScript/Main/constants.txt
- Configuration/TypoScript/Main/setup.txt
- Resources/Private/Partials/Form/Field/Submit.html
- Resources/Private/Templates/Form/Create.html
The framework settings are awesome! I've extended them to the submit button template, which still had the bootstrap classes, and the create message on form send (so users with foundation or other frameworks can configure them via TS)
> Added Constant for submit button framework classes

- Classes/Utility/BackendUtility.php
This should improve the handling of routes in backend.
It especially improves how the correct module name is retrieved, see also: 
\TYPO3\CMS\Backend\RecordList\AbstractRecordList::determineScriptUrl
> [TASK] improve handling of routes in backend

- Classes/ViewHelpers/Misc/GetFileWithPathViewHelper.php
> [BUGFIX] Make sure core exceptions are caught for viewhelper

- Resources/Private/Language/de.locallang.xlf
Bitte höhrere Zahl eintragen! => Bitte höhere Zahl eintragen!
> correcting misspelled text

- Configuration/TypoScript/BootstrapClassesAndLayout/constants.txt
fix bug #206 in constant-editor
> [BUGFIX] constant.txt bootstrapPath is type=text

- Documentation/Faq/Index.rst
This makes it easier to see the list of questions
> [DOC] Table of Contents for FAQ

- .editorconfig
> Add .editorconfig so editors/IDEs can configure themselves automatically

- Classes/ViewHelpers/Validation/AbstractValidationViewHelper.php
- Classes/ViewHelpers/Validation/ValidationDataAttributeViewHelper.php
> Add aria-required="true" to required fields for better accessibility

- readme.md
Mention powermail_cond in readme suggest extensions.
> [TASK] Mention powermail_cond in readme

- Documentation/ForAdministrators/BestPractice/SavingValuesToThirdPartyTables/Index.rst
> [BUGFIX] Fixed typo

- Classes/Domain/Model/Mail.php
Improve usage of signal slots by adding a new property which can hold additional data which is kept over the request
Resolves: #395
> [FEATURE] Add new transient property to model Mail

- Classes/Controller/FormController.php
- Documentation/ForDevelopers/SignalSlots/Index.rst
reference the settings and update documentation, so the developer can modified them in the slot
> #340 initializeObjectSettingsSlot access settings

- Classes/ViewHelpers/Misc/GetFileWithPathViewHelper.php
rels https://github.com/einpraegsam/powermail/issues/368
> [BUGFIX] Backend Module Mail View: Uploads including amp in path get escaped although they shouldn't

- Documentation/ForEditors/FieldHtml.md
The constant htmlForHtmlFields must be set to 1. Give this information already here. This is time saving.
> give the information about the needed constant

- Configuration/TypoScript/BootstrapClassesAndLayout/constants.typoscript
- Configuration/TypoScript/BootstrapClassesAndLayout/setup.typoscript
- Configuration/TypoScript/Main/constants.typoscript
- Configuration/TypoScript/Main/setup.typoscript
- move typoscript setup for bootstrap css
- make bootstrap.important available in constant editor
- fix some typos
- improve comments
> [FEATURE] Improve structure of TypoScript files for bootstrap

- Tests/Behavior/behat-docker.yml
- Tests/Behavior/readme.md
More and more people are using docker for development purposes. So it should
be possible to do theses tests also via docker container.
Resolves: #595
> [FEATURE] Add configuration and docs for behavior tests in docker

- Classes/Domain/Service/Mail/SendDisclaimedMailPreflight.php
> [BUGFIX] Change type for SendDisclaimedMailPreflight

- Classes/Domain/Model/Mail.php
> [BUGFIX] explicitly resolve the LazyLoadingProxy of getFeuser

- Classes/Domain/Validator/CaptchaValidator.php
Resolves: https://github.com/einpraegsam/powermail/issues/376
Resolves: https://projekte.in2code.de/issues/44174
> [BUGFIX] Skip captcha validation of persisted mails (fixes #376)

- Documentation/ForEditors/BackendModule.md
> [DOC] Add hint to section on export

- Classes/ViewHelpers/String/SanitizeCsvCellViewHelper.php
> [BUGFIX] Cast cell value for sanitizeCell to string

- Documentation/ForAdministrators/Privacy.md
While it is probably best not too add too many details about GDPR, I think it might be a good idea to more strongly urge deletion of personal data.
> Add information about GDPR and data retention period

- Configuration/TypoScript/Powermail_Frontend/setup.typoscript
- Resources/Private/Layouts/ContentElements/Export/Default.html
> [BUGFIX] Overwrite the default content element layout for export files to remove the wrapper div

- Documentation/ForDevelopers/AddFinisherClasses.md
pre-defined finishers are 10, 20, 100 (100 = RedirectFinisher)
> AddFinisherClasses: Update pre-defined finishers IDs

- Classes/Domain/Validator/SpamShieldValidator.php
- Classes/ViewHelpers/String/EscapeLabelsViewHelper.php
I was having undefined array keys when using php 8
This commit fixes 2 of them
Cheers
> [BUGFIX] Avoid undefined array key

- Classes/Update/PowermailPermissionSubmoduleUpdater.php
- Classes/Update/PowermailPermissionUpdater.php
> [BUGFIX] Align updater identifiers

- Classes/Update/PowermailPluginUpdater.php
Updated a project and got some warnings
> [BUGFIX] Avoid errors because of warnings/notices

- Resources/Private/Language/locallang_db.xlf
Resolves: https://github.com/in2code-de/powermail/issues/980
> [TASK] Make record type labels singular

- Resources/Private/Templates/Log/SpamNotification.html
Add viewhelper namespace and close if tag
> [BUGFIX] Fix corrupt spam notification template

- Classes/Domain/Model/Mail.php
> [TASK] Ensure correct typed values for getter methods

- Classes/Domain/Service/Mail/SendMailService.php
> [BUGFIX] use -configuration instead -settings

- .github/workflows/testing.yaml
- .project/tests/phpstan-baseline.neon
- .project/tests/phpstan.neon
- .project/typo3/settings.php
- Classes/Controller/ModuleController.php
- Classes/Domain/Validator/CaptchaValidator.php
- Classes/ViewHelpers/Validation/CaptchaViewHelper.php
- Documentation/ForContributors/Readme.md
- composer.json
- add to dev requirements
- add suggested extensions to dev environment
- add phpstan test to github pipeline
- remove some phpstan errors for level 0
Related: in2code-de/powermail#1103
> [FEATURE] Add phpstan as quality tool

- Classes/Controller/ModuleController.php
Related: in2code-de/powermail#1084
> [BUGFIX] Prevent TypeError in ModuleController

- Classes/Tca/FormSelectorUserFunc.php
Related: in2code-de/powermail#1081
> [BUGFIX] Prevent exception, when showing the history of a powermail ce

- Classes/Controller/ModuleController.php
- Resources/Private/Partials/Module/Pagination.html
Related: in2code-de/powermail#1119
> [BUGFIX] Fix pagination in module for email list

- Classes/Update/PowermailPluginUpdater.php
Related: in2code-de/powermail#926
> [BUGFIX] Prevent null value for flexform string

- ext_conf_template.txt
Related: in2code-de/powermail#946
> [BUGFIX] Make extension config field visible in extension settings

- Classes/Domain/Service/Mail/SendReceiverMailPreflight.php
> [BUGFIX] empty subject must not create error flash message

- .project/tests/phpstan-baseline.neon
- Classes/Domain/Validator/SpamShield/ValueBlacklistMethod.php
Thx to @christophlehmann for the PR
Related: in2code-de/powermail#646
> [BUGFIX] Skip boolean values in blacklist string check

- Classes/Tca/ShowFormNoteEditForm.php
- Classes/Tca/ShowFormNoteIfNoEmailOrNameSelected.php
adds int type casting to the usage of pid and uid
> [BUGFIX] Fix #848: Missing type casts

- Configuration/TCA/tx_powermail_domain_model_form.php
Oh man, this is a follow up to #987. Stupid me.
> [BUGFIX] Forms cannot be found in list module search

- Classes/Domain/Repository/MailRepository.php
Related: in2code-de/powermail#755
> [BUGFIX] Make unique validation work for translated forms

- Classes/Domain/Service/Mail/SendMailService.php
Fixes the `SendMailService` to make mail send work again #1112
> Fix receiver mail validation in SendMailService

- Configuration/FlexForms/FlexformPi2.xml
- Configuration/TypoScript/Powermail_Frontend/setup.typoscript
- Documentation/ForAdministrators/PowermailFrontend.md
- Documentation/Readme.md
- Resources/Private/Language/locallang_db.xlf
- Resources/Private/Language/locallang_mod.xlf
Related: in2code-de/powermail#1109
> [CLEANUP] Remove leftovers of fe export functionality

- Documentation/guides.xml
To allow typo3's documentation tool to work with the documentation in this repository some small configuration is needed.
> [TASK] Add guides.xml

- .project/tests/phpstan-baseline.neon
- .project/typo3/additional.php
- Classes/UserFunc/TestForFeature.php
- Classes/Utility/ConfigurationUtility.php
- Configuration/FlexForms/FlexformPi1.xml
- Documentation/ForAdministrators/BestPractice/SendAttachments.md
- Resources/Private/Language/locallang_db.xlf
- ext_localconf.php
https://projekte.in2code.de/issues/66793
> [FEATURE] Allow editors to choose whether attachments are sent

- Classes/Controller/FormController.php
Related: in2code-de/powermail#1186
> [CLEANUP] Remove too chatty logging

- Classes/Hook/PluginPreviewRenderer.php
> [BUGFIX] Handle missing form in flexform data in PluginPreviewRenderer

- ext_tables.sql
Related in2code-de/powermail#1055
> [CLEANUP] Autocreate management db fields
